xcopy c:\Flash\StickyNinjaMissions\src\*.* c:\OnlineRepositories\StickyNinjaMissions\src /Y
xcopy c:\Flash\StickyNinjaMissions\src\UIPackage\*.* c:\OnlineRepositories\StickyNinjaMissions\src\UIPackage /Y
xcopy c:\Flash\StickyNinjaMissions\src\EditorPackage\*.* c:\OnlineRepositories\StickyNinjaMissions\src\EditorPackage /Y
xcopy c:\Flash\StickyNinjaMissions\src\EditorPackage\EditParamUI\*.* c:\OnlineRepositories\StickyNinjaMissions\src\EditorPackage\EditParamUI /Y
xcopy c:\Flash\StickyNinjaMissions\src\EditorPackage\Menu\*.* c:\OnlineRepositories\StickyNinjaMissions\src\EditorPackage\Menu /Y
xcopy c:\Flash\StickyNinjaMissions\src\LicPackage\*.* c:\OnlineRepositories\StickyNinjaMissions\src\LicPackage /Y
xcopy c:\Flash\StickyNinjaMissions\src\AudioPackage\*.* c:\OnlineRepositories\StickyNinjaMissions\src\AudioPackage /Y
xcopy c:\Flash\StickyNinjaMissions\src\AnimPackage\*.* c:\OnlineRepositories\StickyNinjaMissions\src\AnimPackage /Y
xcopy c:\Flash\StickyNinjaMissions\src\AchievementPackage\*.* c:\OnlineRepositories\StickyNinjaMissions\src\AchievementPackage /Y
xcopy c:\Flash\StickyNinjaMissions\src\TextPackage\*.* c:\OnlineRepositories\StickyNinjaMissions\src\TextPackage /Y
xcopy c:\Flash\StickyNinjaMissions\src\PlayerRecordPackage\*.* c:\OnlineRepositories\StickyNinjaMissions\src\PlayerRecordPackage /Y
xcopy c:\Flash\StickyNinjaMissions\src\MobileSpecificPackage\*.* c:\OnlineRepositories\StickyNinjaMissions\src\MobileSpecificPackage /Y
xcopy c:\Flash\StickyNinjaMissions\src\MissionPackage\*.* c:\OnlineRepositories\StickyNinjaMissions\src\MissionPackage /Y
